### ISSUE TITLE
Home 컴포넌트, App.jsx 등에 대한 수정 요청입니다!

### ISSUE THREAD

**Issue by Programming-Seungwan** [2-guys-Javascript/travel-web-app#2]
1. App.jsx에서 korea/exchange 라우트가 빠진 것 같습니다!  https://github.com/2-guys-Javascript/travel-web-app/blob/3fd2c9581adf77b33e8976ecad18be95f44ea611/src/App.jsx#L16-L24

2. Home.jsx 파일에서 h1에 글자 넣고, 스타일링 해주신 것 좋습니다! 다만, 저희 루트 디렉터리(  `'/'` )에서 그냥 아무 문구 없이 korea / japan에서 픽하는 것으로 끈낼지, 아니면 화면 위에 **where to travel?** 같은 문구를 넣어줄지 이건 어떻게 생각하시는지 궁금합니다!

3. 제 이해가 맞는지 확인하기 위해 여쭤봅니다. `/korea`에서는 위에 nav 바가 있고, 여기에서 추후에 저희가 진행할 google map을 띄우고 하는 등의 작업을 진행합니다( `/japan`)도 마찬가지.

4. krNavBar와 jpNavBar에서 "지도"라고 표기하는 것보다는, 이게 각각 /korea 와 /japan으로 라우팅해주고 일정과 지도가 나타나는 url이기에, "내 일정"으로 표기하는 것이 어떨까 싶습니다. 

5. Home.jsx 파일에서 korea와 japan의 디폴트 색상(빨간색)과 hover 시의 색상(노란색)은 어떤 색으로 가져가면 더 이쁠지 저희가 고민해보면 좋을 것 같습니다(이래서 디자이너 필요한 거구나...)

**Comment by manymogo** [comment]
1. -완-

2. 뭐든 좋긴 합니다. 아직 css는 이제야 손보기 시작해야하는 상황이기 때문에 아직 크게 신경쓰지 않아도 될 것 같기는 합니다. 하지만 질문의도가 앞으로 저희 프로젝트의 방향성(앱같은 환경을 구축할 것이냐, 웹에서 동작하는 브라우저의 환경의 특징을 살려서 디자인할 것이냐)에 대한 질문이라면 저는 앱같은 환경을 추구하긴 합니다. 최대한 미니멀한 디자인에 컴팩트한 설계 => 손 쉬운 사용성 => 접근성 이라고 생각하기 때문에… 조금 더 고민해보죠!

3. 맞습니다! 환율 지도(이게 아마 /korea, /japan을 들어왔을때의 메인 페이지겠죠?) 날씨 정보를 출력해주는 라우팅입니다!

4. 어휴 좋습니다!

5. 네 좀 더 충분한 얘기가 오가야 하는 것 같구, 2번 질문에서 말씀드린대로 아직 css의 틀이 잡혀있지 않기 때문에 저는 그냥 직관적으로 Link태그 안에 div를 넣어 기존 하려고 하셨던 텍스트를 중앙으로 가져오는 기능(+ 텍스트 컨텐츠만 따로 css설정이 가능한 것도 가시적으로 표현하기 위해 :hover 적용!)을 표현하기 위한 것 뿐이었습니다! 디자이너가 없는 환경이기 때문에 오히려 더 많은 논의를 해봐야겠네요! 적극적으로 의견 내주시면 감사하겠습니다, 저도 적극적으로 의견을 내겠습니다!

**Comment by Programming-Seungwan** [comment]
넵 고생 많으셨습니다 :) 저 지금 로컬에서 merge 하다가 충돌나서 그거좀 해결해보러 가겠습니다 ....🥲
