### ISSUE TITLE
동준님께 공유했던 firebase 비밀번호 인증 방식과 그 이외에 대한 고민 사항 공유입니다.

### ISSUE THREAD

**Issue by Programming-Seungwan** [2-guys-Javascript/travel-web-app#26]
1. `app.jsx`에서 korea와 japan 탭의 `Route` 컴포넌트들의 `to` 속성에서 앞에 /를 붙이지 않은 이유가 따로 있으신가요?

2. 찬혁님 리뷰에서 보이는 것처럼 `Header.jsx` 파일에서 `Link` 태그 안에 `Button` 태그가 있는 것보다는 `Button` 태그 내부에 `Link` 태그가 있는 것이 더 맞지 않을까 싶습니다(html 구조상) => 동준님도 OK 하시면 수정하도록 하겠습니다!

3. 저희가 만들어준 `Header` 컴포넌트가 현재 component 디렉터리의 바로 하위 path에 위치하는데, 이를 스타일링하는 header.css 파일과 함께 묶을 수 있도록 하나의 디렉터리를 만들어주면 어떨까 싶습니다. 또한 컴포넌트 이름을 그냥 Header에서 다른 구체적인 것으로 바꾸는 것도 어떨까 싶습니다(예를 들면, 해당 헤더는 애플리케이션에서 계속 나타나니까 컴포넌트 이름을 ApplicationHeader 라던지…).

4. 현재 로그인 상태, uid 상태, displayName 상태를 app.jsx 컴포넌트에서 만들어서 관리하고 있습니다(제가 오늘 구현한 비밀번호 인증 방식의 구현에서). 이때 상태들을 바꾸는 핸들링 함수들을 하위 컴포넌트들에게 전달하지 않고, setState 함수들만을 prop으로 전달하여, 실제 핸들러 함수는 하위 컴포넌트에서 만들어서 적용하는 방식을 택하고 있습니다. 그냥 핸들러 함수까지 App.jsx 파일에서 만들어서 전달할지 아니면 지금처럼 그냥 setState 함수만을 전달할지 여쭤보고 싶습니다.  => 근데 전달되는 속성명이 onChange뭐시기~ 니까 핸들러 함수를 App 컴포넌트에서 만들어서 전달하는 방식이 괜찮을 것 같다고 개인적으로 생각은 합니다.

**Comment by manymogo** [comment]
1. 큰 의미는 없습니다!
2. 네네 관계 없습니다!
3. 좋습니다!
4. 승완님이 괜찮다고 느끼는 방식대로 진행하셔도 좋을 것 같습니다!
