### ISSUE TITLE
현재 생각하고 있는 지도 탭에 대한 포인트입니다.

### ISSUE THREAD

**Issue by Programming-Seungwan** [2-guys-Javascript/travel-web-app#28]
저희가 Japan 컴포넌트, 즉 지도 일정 탭에서 어떤 것을 보여줄지(기능)과 관련하여 어떤 상태가 필요하고 이를 어떻게 변화시키는 로직이 있을지 고민해 보았습니다.

1. 로그인이 되지 않은 상태이면 NonLogInMap 컴포넌트를, 로그인이 된 상태이면 LogInMap 컴포넌트를 렌더링합니다. 이는 userId 상태를 방아서 렌더링할 수 있습니다 => 추후에 isLoggedIn 상태가 필요 없을지도? 그냥 userId로 퉁쳐버릴 수도 있을 것 같아요
2. 로그인 된 사용자가 보는 지도에서, 일정으로서 표시되는 마커와 그냥 사용자가 찍는 마커가 구분되어야 할 것 같습니다(색깔 같은 것으로). 현재 저희가 같이 라이브 코딩으로 만든 NonLogInMap 컴포넌트에서는 찍는 족족 계속 마커가 생기는데, 이렇게 배열로 관리할 것은 일정 상태이고, 사용자가 pick하는 마커는 다른 지점을 pick하면 기존의 마커는 사라지고, 새로운 지점에 마커가 생겨야할 것 같습니다.
3. 선택된 날짜에 따라서 일정 마커는 변경되어야 합니다. 그리고 처음에 로그인된 사용자가 지도탭에 들어왔을 때에는 그냥 빈 지도를 보여주며 날짜를 선택하라고 할 것인지, 아니면 첫 일정의 지도를 보여줄 것인지를 정하면 좋을 것 같아요. 사실 생각해보면 아직 일정을 하나도 생성하지 않은 사용자가 들어온 상황까지 고려해야하기 때문에 전자의 방식이 맞지 않을까 싶습니다.
4. Place API를 주변 관광 명소를 `AutoComplete` 컴포넌트를 통해 검색하려면 `libraries` 필드에 `['places']`를 명시하면 되기는 합니다. 다만, 제가 지금 해보고 있는 작업은 저희가 useJsApiLoader() 함수를 통해 isLoaded를 생성하여 구글 맵을 생성하는 방법인데.....
=> 아 그냥 무시하셔도 좋을 것 같습니다 LoadScript 컴포넌트를 사용하면 처음 지도 탭에 접속됐을 때에는 괜찮은데, 다른 탭으로 이동했다가 다시 지도 탭으로 돌아왔을 떄 문제가 생기네요. 그냥 useJsApiLoader()를 사용하는 것이 더 낫겠습니다

**Comment by manymogo** [comment]
1. 넵 맞습니다! 지금도 사실 퉁칠 수 있긴 합니다 ㅋㅋㅋ 나중에 로그인 상태 유지 + 로그아웃까지 다 구현한 상태에서 수정해보도록 하죠..!
2. 로그인 안한 상태에서는 마커 기능을 꺼버리는게 좋을 것 같습니다 + 아직 마커 찍기밖에 구현을 안해서 더 어색하게 보여지긴 합니다 ㅋㅋㅋ 마커 찍으면서 동시에 마커 찍은 곳을 중심으로 이동 + 마커에 정보 넣기 등등 이런 거랑 승완님이 말씀하신 것처럼 마커 삭제, 마커 정보 보기 등 그런 클릭 이벤트를 따로 추가해주면 찍는 족족 마커 생기는 어색함이 사라질 것 같습니다.
3. 마커를 추가하지 않은 상태라면 빈 상태의 맵을 보여주고, 마커를 맞는 날짜에 추가해놓은 상태라면 (로그인 상태) 날짜에 맞춰서 보여주는게 맞다고 생각합니다. 날짜에 따른 마커를 추가 + 저장을 마커를 찍을 때부터 마커 정보 입력칸에 이름: 내용: 날짜: 시간: 이 정도로 구분해서 해주면 될 것 같습니다. 
4. ㅋㅋㅋ 저는 관련해서 한국탭에서의 정보는 google place로 가져오면 진짜 별거 없을거라.., 네이버나 카카오에서 가져와야할지 혼자 아직 벌어지지 않은 고민을 했습니다... 🧐
