### ISSUE TITLE
로그인 지도 화면에서 저장된 일정이 해당 날짜 이 외의 날짜에서도 출력되는 카테고리를 만들었으면 좋겠습니다!

### ISSUE THREAD

**Issue by manymogo** [2-guys-Javascript/travel-web-app#69]
현재는 저장된 일정을 현재의 날짜에서만 (2023년 11월 3일이면 2023년 11월 3일의 일정만)불러오는 중인데,
현재의 기능 자체는 일정이 많아지다보면 헷갈릴 수 있다보니 좋다고 생각합니다.
다만 전체 일정을 관리하기 힘들다고 느낀 부분이 제가 2024년 3월 30일에 일정을 새로 만들었는데,
까먹게 되면 당일이 오기 전까지 찾을 수가 없을 것 같더라구요... 🥲
그래서 (오늘 일정보기 / 전체 일정보기) 이런 식으로 토글버튼을 만들어서 일정을 가져오는 기능이 추가되어야 할 것 같습니다.
실제로 여행을 갔을 때 여행 전체 일정을 넓게 보고 싶은 경우가 더 많을거라고 생각하기도 하구요..!

**Comment by Programming-Seungwan** [comment]
그렇다면 오늘 일정보기, 전체 일정 보기는 나누어서 생각해야할 것 같아요. 본 이슈는 일단 닫아주고, 두개를 분리해서 이슈로 발행하도록 하겠습니다 :)
