### ISSUE TITLE
InfoWindow의 내용이 빈약한 것 같습니다!

### ISSUE THREAD

**Issue by manymogo** [2-guys-Javascript/travel-web-app#70]
현재는 식당이나 카페의 이름만 출력하는 단조로운 형식의 Window창이 뜨고 있는데,
모바일 기기로 화면을 확인하기에 너무 작은 느낌도 존재하고, 비 로그인 지도 컴포넌트에 식당, 카페 리스트처럼은 아니더라도
셀렉한 식당이나 카페의 간단한 정보는 출력해주는 편이 좋을 것 같다고 생각합니다! 
1안으로는 비로그인 컴포넌트처럼 리스트를 출력하는 탭을 만들어서 비로그인 컴포넌트에서의 방식과 동일한 방식으로 출력한다.
2안으로는 셀렉한 마커에 식당 정보만 가져와서 지도 하단에 표시해준다.
이 정도로 정리할 수 있을 것 같습니다!

**Comment by Programming-Seungwan** [comment]
해당 이슈를 기능 구현해주었습니다 :)
