### ISSUE TITLE
스타일링과 try ~ catch 구문에 대한 논의 지점입니다!

### ISSUE THREAD

**Issue by Programming-Seungwan** [2-guys-Javascript/travel-web-app#9]
1. 현재 저희가 Home 컴포넌트의 korea, japan 글자를 스타일링 하기위해 Home.css에 `h1`에 대한 스타일링을 해주었습니다. 현재 이것이 날씨 탭의 **“일본 날씨입니다”** 텍스트가 `h1`이라 영향을 미치는 것 같습니다. 두 케이스 모두 `h1`와 같은 태그명 selector를 사용하지 않고 클래스명을 통한 방식으로 해야 충돌이 나지 않을 것 같습니다. => 추가적으로 **“일본 날씨입니다”** 텍스트에는 transition까지 의도치 않게 적용됩니다. 
2. Jpweather 컴포넌트의 데이터를 불러오는 로직에서 `try ~ catch`문의 catch에 setError()구문이 있습니다. 하지만 코드를 보면 error라는 상태는 아직 컴포넌트 내에서 만들어진 적이 없습니다. 혹시 이를 만들어주고, weather-day 클래스의 `ul` 태그에 이를 `&&` 연산자를 이용하여 에러가 뜰 때 표기해주시려고 하신 것인지 궁금합니다.

**Comment by manymogo** [comment]
1. 네 좋습니다 되도록이면 태그명보다 클래스명을 활용해서 스타일링 하도록 해요!! 
2. 아 ㅋㅋㅋㅋㅋㅋㅋ 그거 error 라는 상태를 만들어서 승완님이 말씀하신대로 현재 날씨 보여주는 div 태그 안에 error일 때 보여주게끔 했는데, 지금은 지워도 관계 없을 것 같습니다! 제가 실수로 안 지운 것 같습니다..! 🥲
